# https://docs.docker.com/get-started/kube-deploy/#describing-apps-using-kubernetes-yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1
---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8888
    targetPort: 8888
