# https://docs.docker.com/get-started/kube-deploy/#describing-apps-using-kubernetes-yaml
# https://stackoverflow.com/questions/39484653/mapping-incoming-port-in-kubernetes-service-to-different-port-on-docker-containe

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
  labels:
    app: wil-playground
spec:
  selector:
    matchLabels:
      app: wil-playground
  replicas: 1
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
        - name: playground
          image: wil42/playground:v1
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
