# https://docs.docker.com/get-started/kube-deploy/#describing-apps-using-kubernetes-yaml
# https://stackoverflow.com/questions/39484653/mapping-incoming-port-in-kubernetes-service-to-different-port-on-docker-containe

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v2

---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - port: 8888
    targetPort: 8888
